postgres:
  image: "postgres:9.6.5"
  restart: on-failure
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: db
    PGDATA: /var/lib/postgresql/data

nginx:
  image: nginx:1.13.7
  restart: on-failure
  ports:
    - "8080:80"
  links:
    - backend
  volumes:
    - "./conf/nginx.conf:/etc/nginx/nginx.conf:ro"
    - "./static/:/etc/nginx/static/:ro"

backend:
  image: "banking"
  restart: on-failure
  links:
    - postgres
  volumes:
    - ".:/go/src/internetBanking:ro"

shell:
  image: "banking"
  command: "bash"
  links:
    - postgres
  volumes:
    - ".:/go/src/internetBanking"
