postgres:
  image: "postgres:9.6.5"
  restart: on-failure
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: db
    PGDATA: /var/lib/postgresql/data

backend:
  image: "banking"
  restart: on-failure
  links:
    - "postgres"
  volumes:
    - ".:/go/src/internetBanking:ro"

frontend:
  image: "teracy/angular-cli"
  restart: on-failure
  working_dir: "/ui/"
  entrypoint: "ng serve --host 0.0.0.0 --port 80 --disable-host-check"
  volumes:
    - "./ui/:/ui/"

nginx:
  image: nginx:1.13.7
  restart: on-failure
  ports:
    - "8080:80"
  links:
    - "backend"
    - "frontend"
  volumes:
    - "./conf/nginx.conf:/etc/nginx/nginx.conf:ro"
