postgres:
  image: "postgres:9.6.5"
  restart: on-failure
  ports:
    - "5432:5432"
  environment:
    POSTGRES_USER: postgres
    POSTGRES_PASSWORD: postgres
    POSTGRES_DB: db
    PGDATA: /var/lib/postgresql/data

server:
  image: "banking"
  restart: on-failure
  ports:
    - "8080:8080"
  links:
    - postgres
  volumes:
    - ".:/go/src/internetBanking:ro"

shell:
  image: "banking"
  command: "bash"
  links:
    - postgres
  volumes:
    - ".:/go/src/internetBanking"
